# Generated by Django 4.0.3 on 2022-04-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('tl_id', models.AutoField(primary_key=True, serialize=False)),
                ('tl_titulo', models.CharField(max_length=500)),
                ('tl_description', models.CharField(max_length=500)),
                ('tl_date', models.DateField()),
                ('tl_task', models.CharField(max_length=500)),
                ('tl_state', models.BooleanField()),
            ],
        ),
    ]
